accelerate launch run_lora_inference.py \
  --pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0 \
  --pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix \
  --output_dir=runs/lora_v1/ \
  --lora_checkpoint_path=runs/lora_v1/checkpoint-xxxx/ \
  --resolution=1024 \
  --num_images_to_generate=4 \
  --guidance_scale=5.0 \
  --num_inference_steps=40 \
  --prompt="A picture of an old man, looking at the camera, close view" \
  --negative_prompt="missing limbs, disfigured, deformed, crippled"